<<<<<<< HEAD
# Generated by Django 3.0.7 on 2020-11-07 20:23
=======
# Generated by Django 3.0.8 on 2020-11-07 21:15
>>>>>>> main

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
<<<<<<< HEAD
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('contacts', models.ManyToManyField(blank=True, null=True, related_name='_contact_contacts_+', to='website.Contact')),
=======
            name='Announcement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(default='', max_length=32)),
>>>>>>> main
            ],
        ),
    ]
