# Generated by Django 3.0.7 on 2020-11-07 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='contacts',
        ),
        migrations.AddField(
            model_name='contact',
            name='contacts',
            field=models.TextField(default='', null=True),
        ),
    ]
