# Generated by Django 3.0.8 on 2020-11-07 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(default='', max_length=32)),
                ('contacts', models.ManyToManyField(blank=True, related_name='_person_contacts_+', to='website.Person')),
            ],
        ),
    ]
