# Generated by Django 3.0.7 on 2020-11-07 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_auto_20201107_2050'),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('contacts', models.ManyToManyField(blank=True, default=None, related_name='_person_contacts_+', to='website.Person')),
            ],
        ),
        migrations.DeleteModel(
            name='Contact',
        ),
    ]
