# Generated by Django 3.0.8 on 2020-11-07 22:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_person'),
    ]

    operations = [
        migrations.RenameField(
            model_name='person',
            old_name='text',
            new_name='name',
        ),
    ]
